# Generated by Django 5.2.15 on 2026-06-20 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_repartidor', models.CharField(max_length=100)),
                ('email_repartidor', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100)),
                ('tarifa_por_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_envio', models.DateField()),
                ('repartidor_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMiniCore.repartidor')),
                ('zona_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMiniCore.zona')),
            ],
        ),
    ]
